### ISSUE TITLE
Error in composer.json of v1.2.0

### ISSUE THREAD

**Issue by fritzmg** [dklemmt/contao_dk_masonry#1]
Version 1.2.0 in the [Extension Repository](https://contao.org/de/extension-list/view/dk_masonry.de.html) lists the compatible Contao versions for this release as `3.2.0` to `3.4.0`.

However, the composer.json of the [tagged 1.2.0 release here on Github](https://github.com/dklemmt/contao_dk_masonry/tree/1.2.0) still has the following requirement `"contao/core": ">=3.0.5,<3.2",` and thus the 1.2.0 release is not installable under Contao 3.2 or greater via Composer.

**Comment by dklemmt** [comment]
was fixed in 1.2.1
