### ISSUE TITLE
 Warning: Undefined array key "numberOfItems"  

### ISSUE THREAD

**Issue by hjuefricke** [dklemmt/contao_dk_masonry#12]
Hallo,

vielen Dank für die Extension. 

Unter php 8 gibt es beim Erneuern des Dev-Cache und im Debug-Modus leider eine unschöne Warnung:
Warning: Undefined array key "numberOfItems"  in tl_content.php line 259

Es funzt wieder, wenn man in der Sprachdatei "languages/en/tl_content.php" Zeile 32 ersetzt durch:
$GLOBALS['TL_LANG']['tl_content']['dk_msryNumberOfItems'] = $GLOBALS['TL_LANG']['MSC']['numberOfItems'];

Herzliche Grüße
Hjue

**Comment by fritzmg** [comment]
This is actually an error that happens because of Contao 4.12, not PHP 8 specifically. In Contao 4.12, the `numberOfItems`  translation was moved to `MSC`.

**Comment by fritzmg** [comment]
Should be fixed in `1.2.3`.

**Comment by hjuefricke** [comment]
Ok, thanks for the correction!
And thanks for the quick reaction.
