### ISSUE TITLE
Upgrader für Contao 5.3

### ISSUE THREAD

**Issue by Schmidty2** [dklemmt/contao_dk_masonry#13]
Hallo,
ist ein Upgrade für Contao 5.3 geplant?
Ich benötige einen Preis für die Aktualisierung und das Update für Contao 5.3.
Wenn ich einen Preis für die Aktualisierung und das Upgrade weiß, kann ich die (Teil-)Finanzierung klären.
Rückmeldung gerne per PN, Danke.

**Comment by fritzmg** [comment]
This extension is now unlocked for Contao 5.
